export const EpicsData = {
  epics: [
    {
      name: 'Voice Command Task Management',
      type: 'epic',
      storyPoint: 37,
      children: [
        {
          name: 'Create tasks using voice commands',
          type: 'story',
          storyPoint: 16,
          children: [
            {
              name: '[Frontend] Implement voice command interface for task creation',
              type: 'task',
              storyPoint: 5,
              key: 'epic:1;story:1;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Develop API for processing voice to create tasks',
              type: 'task',
              storyPoint: 5,
              key: 'epic:1;story:1;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Voice command task creation feature',
              type: 'task',
              storyPoint: 3,
              key: 'epic:1;story:1;task:3',
              sprintKey: '',
            },
            {
              name: '[iOS] Voice command task creation feature',
              type: 'task',
              storyPoint: 3,
              key: 'epic:1;story:1;task:4',
              sprintKey: '',
            },
          ],
          key: 'epic:1;story:1',
        },
        {
          name: 'Update tasks status using voice',
          type: 'story',
          storyPoint: 21,
          children: [
            {
              name: '[Frontend] Add voice recognition for task status updates',
              type: 'task',
              storyPoint: 5,
              key: 'epic:1;story:2;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Create API endpoint for task status modification via voice',
              type: 'task',
              storyPoint: 5,
              key: 'epic:1;story:2;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Implement voice-driven task status updates',
              type: 'task',
              storyPoint: 3,
              key: 'epic:1;story:2;task:3',
              sprintKey: '',
            },
            {
              name: '[iOS] Implement voice-driven task status updates',
              type: 'task',
              storyPoint: 3,
              key: 'epic:1;story:2;task:4',
              sprintKey: '',
            },
            {
              name: '[Backend] Integrate natural language processing for task status interpretation',
              type: 'task',
              storyPoint: 5,
              key: 'epic:1;story:2;task:5',
              sprintKey: '',
            },
          ],
          key: 'epic:1;story:2',
        },
      ],
      key: 'epic:1',
    },
    {
      name: 'Voice-to-Text Project Notes',
      type: 'epic',
      storyPoint: 34,
      children: [
        {
          name: 'Dictate and transcribe project notes',
          type: 'story',
          storyPoint: 13,
          children: [
            {
              name: '[Frontend] Implement voice-to-text for note-taking',
              type: 'task',
              storyPoint: 5,
              key: 'epic:2;story:1;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Develop transcription service for voice notes',
              type: 'task',
              storyPoint: 5,
              key: 'epic:2;story:1;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Add voice note dictation feature',
              type: 'task',
              storyPoint: 3,
              key: 'epic:2;story:1;task:3',
              sprintKey: '',
            },
          ],
          key: 'epic:2;story:1',
        },
        {
          name: 'Review and edit transcribed notes with voice',
          type: 'story',
          storyPoint: 21,
          children: [
            {
              name: '[Frontend] Enable voice command editing for transcribed notes',
              type: 'task',
              storyPoint: 5,
              key: 'epic:2;story:2;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Implement voice command recognition for note editing',
              type: 'task',
              storyPoint: 5,
              key: 'epic:2;story:2;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Voice editing for project notes',
              type: 'task',
              storyPoint: 3,
              key: 'epic:2;story:2;task:3',
              sprintKey: '',
            },
            {
              name: '[iOS] Voice editing for project notes',
              type: 'task',
              storyPoint: 3,
              key: 'epic:2;story:2;task:4',
              sprintKey: '',
            },
            {
              name: '[Backend] Natural language processing for editing commands',
              type: 'task',
              storyPoint: 5,
              key: 'epic:2;story:2;task:5',
              sprintKey: '',
            },
          ],
          key: 'epic:2;story:2',
        },
      ],
      key: 'epic:2',
    },
    {
      name: 'Voice-Activated Navigation',
      type: 'epic',
      storyPoint: 34,
      children: [
        {
          name: 'Navigate software with voice commands',
          type: 'story',
          storyPoint: 13,
          children: [
            {
              name: '[Frontend] Implement voice-activated navigation',
              type: 'task',
              storyPoint: 5,
              key: 'epic:3;story:1;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Develop voice command routing logic',
              type: 'task',
              storyPoint: 5,
              key: 'epic:3;story:1;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Add voice navigation feature',
              type: 'task',
              storyPoint: 3,
              key: 'epic:3;story:1;task:3',
              sprintKey: '',
            },
          ],
          key: 'epic:3;story:1',
        },
        {
          name: 'Voice command search for tasks or projects',
          type: 'story',
          storyPoint: 21,
          children: [
            {
              name: '[Frontend] Implement voice search functionality',
              type: 'task',
              storyPoint: 5,
              key: 'epic:3;story:2;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Create search API for voice queries',
              type: 'task',
              storyPoint: 5,
              key: 'epic:3;story:2;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Develop voice-driven search feature',
              type: 'task',
              storyPoint: 3,
              key: 'epic:3;story:2;task:3',
              sprintKey: '',
            },
            {
              name: '[iOS] Develop voice-driven search feature',
              type: 'task',
              storyPoint: 3,
              key: 'epic:3;story:2;task:4',
              sprintKey: '',
            },
            {
              name: '[Backend] Integrate NLP for search query interpretation',
              type: 'task',
              storyPoint: 5,
              key: 'epic:3;story:2;task:5',
              sprintKey: '',
            },
          ],
          key: 'epic:3;story:2',
        },
      ],
      key: 'epic:3',
    },
    {
      name: 'Customizable Voice Commands',
      type: 'epic',
      storyPoint: 34,
      children: [
        {
          name: 'Customize voice commands for personal speech patterns',
          type: 'story',
          storyPoint: 13,
          children: [
            {
              name: '[Frontend] Create interface for voice command customization',
              type: 'task',
              storyPoint: 5,
              key: 'epic:4;story:1;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Develop customization options for voice commands',
              type: 'task',
              storyPoint: 5,
              key: 'epic:4;story:1;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Implement customization of voice commands',
              type: 'task',
              storyPoint: 3,
              key: 'epic:4;story:1;task:3',
              sprintKey: '',
            },
          ],
          key: 'epic:4;story:1',
        },
        {
          name: 'Train voice recognition for improved accuracy',
          type: 'story',
          storyPoint: 21,
          children: [
            {
              name: '[Frontend] Add voice recognition training module',
              type: 'task',
              storyPoint: 5,
              key: 'epic:4;story:2;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Implement machine learning for voice recognition training',
              type: 'task',
              storyPoint: 5,
              key: 'epic:4;story:2;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Feature for training voice recognition',
              type: 'task',
              storyPoint: 3,
              key: 'epic:4;story:2;task:3',
              sprintKey: '',
            },
            {
              name: '[iOS] Feature for training voice recognition',
              type: 'task',
              storyPoint: 3,
              key: 'epic:4;story:2;task:4',
              sprintKey: '',
            },
            {
              name: '[Backend] Data collection for voice recognition improvement',
              type: 'task',
              storyPoint: 5,
              key: 'epic:4;story:2;task:5',
              sprintKey: '',
            },
          ],
          key: 'epic:4;story:2',
        },
      ],
      key: 'epic:4',
    },
    {
      name: 'Integration with Other Tools',
      type: 'epic',
      storyPoint: 34,
      children: [
        {
          name: 'Integrate with email and calendar',
          type: 'story',
          storyPoint: 13,
          children: [
            {
              name: '[Frontend] Design integration interface for email and calendar',
              type: 'task',
              storyPoint: 5,
              key: 'epic:5;story:1;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Develop API for email and calendar integration',
              type: 'task',
              storyPoint: 5,
              key: 'epic:5;story:1;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Implement email and calendar integration',
              type: 'task',
              storyPoint: 3,
              key: 'epic:5;story:1;task:3',
              sprintKey: '',
            },
          ],
          key: 'epic:5;story:1',
        },
        {
          name: 'Link with invoicing software',
          type: 'story',
          storyPoint: 21,
          children: [
            {
              name: '[Frontend] Create interface for invoicing software linkage',
              type: 'task',
              storyPoint: 5,
              key: 'epic:5;story:2;task:1',
              sprintKey: '',
            },
            {
              name: '[Backend] Build API for connecting to invoicing platforms',
              type: 'task',
              storyPoint: 5,
              key: 'epic:5;story:2;task:2',
              sprintKey: '',
            },
            {
              name: '[Android] Develop feature to connect with invoicing tools',
              type: 'task',
              storyPoint: 3,
              key: 'epic:5;story:2;task:3',
              sprintKey: '',
            },
            {
              name: '[iOS] Develop feature to connect with invoicing tools',
              type: 'task',
              storyPoint: 3,
              key: 'epic:5;story:2;task:4',
              sprintKey: '',
            },
            {
              name: '[Backend] Ensure secure data transfer with invoicing software',
              type: 'task',
              storyPoint: 5,
              key: 'epic:5;story:2;task:5',
              sprintKey: '',
            },
          ],
          key: 'epic:5;story:2',
        },
      ],
      key: 'epic:5',
    },
  ],
};
