export const STRIPE_CONFIG = {
  SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  VITE_PUBLISHABLE_KEY: process.env.VITE_STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
} as const;
