import { useRef, useState } from 'react';
import { CloseOutlined, UploadOutlined } from '@ant-design/icons';
import { Access, DOCTYPE } from '@prisma/client';
import type { InputRef } from 'antd';
import { Button, Flex, Input, message, Upload } from 'antd';
import * as mammoth from 'mammoth';
import * as pdfjsLib from 'pdfjs-dist';
import { useNavigate } from 'react-router';

import ProjectStep from '../../../common/components/ProjectStep';
import ScrollingPrompts from '../../../common/components/ScrollingPrompts';
import { useCurrentUser } from '../../../common/contexts/currentUserContext';
import { useLanguage } from '../../../common/contexts/languageContext';
import { GlobalStoreInst } from '../../../common/util/globalStore';
import trackEvent from '../../../trackingClient';
import { useAddProjectMutation } from '../../project/hooks/useProjectMutation';

interface ProjectCardProps {
  selectedCategory?: string;
}

export function ProjectCard({ selectedCategory }: ProjectCardProps) {
  const { t } = useLanguage();
  const [isSaving, setIsSaving] = useState(false);
  const [projectName, setProjectName] = useState('');
  const [uploadedText, setUploadedText] = useState('');
  const [uploadedFileName, setUploadedFileName] = useState<string | null>(null);
  const { user } = useCurrentUser();
  const navigate = useNavigate();
  const inputRef = useRef<InputRef>(null);

  const { createProjectMutation } = useAddProjectMutation({
    onSuccess: (project) => {
      setIsSaving(false);
      const prd = project.documents.find((doc) => doc.type === DOCTYPE.PRD);
      if (prd) {
        GlobalStoreInst.set('autoGenerateDocForPRD', prd.id);
        navigate(`/docs/${prd.id}`, {
          state: { autoCollapseSidepanel: true },
        });
      }
    },
    onError: () => {
      setIsSaving(false);
    },
  });

  const onSave = () => {
    if (!projectName && !uploadedText) {
      message.info('Please describe what you want to build or upload a file.');
      return;
    }

    const dateValue = new Date();

    // 存入全局：传给 ChatBox 使用
    if (uploadedText) {
      const fileExtension = uploadedFileName?.split('.').pop()?.toLowerCase();
      const isImage = ['jpg', 'jpeg', 'png', 'gif', 'webp'].includes(
        fileExtension || ''
      );

      GlobalStoreInst.set('uploadedFileInfoForPRD', {
        uploadedText,
        uploadedFilename: uploadedFileName,
        uploadedFileType: fileExtension,
        isImage: isImage,
      });
    }

    createProjectMutation.mutate({
      name: projectName,
      description: '', //这里是对应projectInfo里面的description
      access: Access.SELF,
      dueDate: dateValue,
      ownerUserId: user?.id,
    });

    setIsSaving(true);

    trackEvent('startProjectClientClicked', {
      name: projectName,
      ownerUserId: user?.id,
      dueDate: dateValue,
    });
  };

  const handleUpload = async (file: File) => {
    const allowedTypes = [
      'text/plain',
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'image/jpeg',
      'image/jpg',
      'image/png',
      'image/gif',
      'image/webp',
    ];

    if (!allowedTypes.includes(file.type)) {
      message.error(
        'Unsupported file type. Please upload a .txt, .pdf, .docx, or image file.'
      );
      return false;
    }

    setUploadedFileName(file.name);

    let extractedText = '';

    try {
      if (file.type === 'text/plain') {
        const reader = new FileReader();
        reader.onload = () => {
          setUploadedText((reader.result as string).trim());
        };
        reader.readAsText(file);
      } else if (file.type.startsWith('image/')) {
        // Handle image files - convert to base64 for storage
        const reader = new FileReader();
        reader.onload = () => {
          const base64String = reader.result as string;
          setUploadedText(base64String);
        };
        reader.readAsDataURL(file);
      } else if (file.type === 'application/pdf') {
        pdfjsLib.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjsLib.version}/legacy/build/pdf.worker.min.mjs`;
        const loadingTask = pdfjsLib.getDocument({
          data: await file.arrayBuffer(),
        });
        const pdf = await loadingTask.promise;
        let pdfText = '';

        for (let i = 0; i < pdf.numPages; i++) {
          const page = await pdf.getPage(i + 1);
          const textContent = await page.getTextContent();
          const pageText = textContent.items
            .map((item) => ('str' in item ? item.str : ''))
            .join(' ');
          pdfText += pageText + '\n\n';
        }

        extractedText = pdfText.trim();
        setUploadedText(extractedText);
      } else if (
        file.type === 'application/msword' ||
        file.type ===
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      ) {
        const arrayBuffer = await file.arrayBuffer();
        const result = await mammoth.extractRawText({ arrayBuffer });
        extractedText = result.value.trim();
        setUploadedText(extractedText);
      }
    } catch (error) {
      console.error('File parsing failed:', error);
      message.error(t('home.failedToReadFile'));
    }

    return false; // prevent default upload
  };

  const removeUploadedFile = () => {
    setUploadedFileName(null);
    setUploadedText('');
  };

  return (
    <Flex vertical gap={30} align="center">
      <div style={{ width: '100%', display: 'flex', justifyContent: 'center' }}>
        <ProjectStep />
      </div>

      <div
        style={{
          position: 'relative',
          width: 700,
          background: 'white',
          borderRadius: 16,
          padding: 24,
          minHeight: 180,
        }}
      >
        <div
          style={{
            position: 'relative',
            boxShadow: '0 8px 24px rgba(0, 102, 255, 0.1)',
          }}
        >
          <Input.TextArea
            ref={inputRef}
            autoSize={{ minRows: 2, maxRows: 3 }}
            placeholder=""
            value={projectName}
            onChange={(e) => setProjectName(e.target.value)}
            style={{
              fontSize: 16,
              padding: '16px 16px 60px 20px',
              borderRadius: 12,
              resize: 'none',
            }}
          />

          {/* Scrolling prompts placeholder */}
          {!projectName && !uploadedFileName && (
            <div
              style={{
                position: 'absolute',
                top: '16px',
                left: '20px',
                right: '20px',
                pointerEvents: 'none',
                zIndex: 0,
              }}
            >
              <ScrollingPrompts selectedCategory={selectedCategory} />
            </div>
          )}

          {/* upload button*/}
          <div
            style={{
              position: 'absolute',
              bottom: 12,
              left: 16,
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              zIndex: 1,
              maxWidth: '60%', // 避免太长
            }}
          >
            <Upload showUploadList={false} beforeUpload={handleUpload}>
              <Button icon={<UploadOutlined />} size="small" />
            </Upload>

            {uploadedFileName && (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  background: '#f5f5f5',
                  padding: '4px 8px 4px 8px',
                  borderRadius: 6,
                  fontSize: 12,
                  height: 32,
                  maxWidth: 200,
                }}
              >
                <span
                  style={{
                    flex: 1,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                    paddingRight: 8,
                  }}
                  title={uploadedFileName} // 鼠标悬停显示完整文件名
                >
                  {uploadedFileName}
                </span>
                <CloseOutlined
                  onClick={removeUploadedFile}
                  style={{ cursor: 'pointer', fontSize: 10, flexShrink: 0 }}
                />
              </div>
            )}
          </div>

          {/* submit button */}
          <Button
            type="primary"
            icon={<span>✨</span>}
            loading={isSaving}
            onClick={onSave}
            style={{
              position: 'absolute',
              bottom: 8,
              right: 8,
              height: 32,
              borderRadius: 8,
            }}
          >
            {t('home.buildProject')}
          </Button>
        </div>
      </div>

      {/* <Flex gap={12} wrap justify="center" style={{ maxWidth: 700 }}>
        {prompts.map(({ icon, label, prompt, hoverStyle }) => (
          <div
            key={label}
            onClick={() => setProjectName(prompt)}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              padding: '8px 16px',
              borderRadius: 20,
              border: '1px solid #ddd',
              cursor: 'pointer',
              fontSize: 14,
              transition: 'all 0.3s',
            }}
            onMouseEnter={(e) => {
              Object.assign(e.currentTarget.style, hoverStyle);
              e.currentTarget.style.fontWeight = 'bold';
            }}
            onMouseLeave={(e) => {
              Object.assign(e.currentTarget.style, {
                background: '',
                borderColor: '#ddd',
                fontWeight: 'normal',
              });
            }}
          >
            <span>{icon}</span>
            <span>{label}</span>
          </div>
        ))}
      </Flex> */}
    </Flex>
  );
}
