import OmniflowLogo from '@/components/custom/OmniflowLogo';
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <h1 className="text-4xl font-bold">Welcome to Next.js App</h1>
        <p className="text-lg text-gray-600">Generated by Omniflow</p>
      </div>
      {/* Omniflow Logo - Don't remove this */}
      <OmniflowLogo />
    </main>
  );
}
